### ISSUE TITLE
No database file 

### ISSUE THREAD

**Issue by felisane123** [sunjava11/Ecommerce-CodeIgniter#5]
Hey can you please provide the database

**Comment by sunjava11** [comment]
Yes, I will push the database as well

**Comment by jeffebido** [comment]
I wait for the database. Thank you!

**Comment by harydj** [comment]
there's no database inside the project :(

**Comment by sunjava11** [comment]
I will attach the database as well

**Comment by felisane123** [comment]
Hi any news about the database ?

**Comment by sunjava11** [comment]
Yes, I'll attach it today in 2 or 3 hours

**Comment by felisane123** [comment]
Hello sir I still waiting for the database

**Comment by sunjava11** [comment]
Hello guys, sorry for the delay. I've attached the database in the project now.
